# Frontend Dockerfile
FROM node:18-alpine as frontend_build

# Set the working directory
WORKDIR /app/frontend

# Copy package.json and package-lock.json
COPY package.json .

# Install dependencies
RUN npm install

# Copy the rest of the frontend source code
COPY . .

# build the app
RUN npm run build

# Expose the Vite development server port (if needed for dev)
EXPOSE 5173

FROM node:18-alpine as frontend_image

WORKDIR /app/frontend

COPY --from=frontend_build /app/frontend/dist/ /app/frontend/dist/

# Start the Vite development server (adjust if needed)
CMD ["npm", "run", "pre"]