# Frontend Dockerfile
FROM node:18 as FRONTEND_BUILD

# Set the working directory
WORKDIR /app/frontend

# Copy package.json and package-lock.json
COPY package.json .

# Install dependencies
RUN npm install

# Copy the rest of the frontend source code
COPY . .

# # build the app
# RUN npm run build

# # staging production server
# FROM node:18 as FRONTEND_IMAGE

# # setting up the directory
# WORKDIR /app/frontend

# # copy the build
# COPY --from=FRONTEND_BUILD /app/frontend/dist/ /app/frontend/dist/

RUN npm install vite

EXPOSE 5173

# COPY package.json .

# COPY vite.config.js .

# Start the Vite development server
CMD ["npm", "run", "dev"]